flask_app/app/models/Director.py
from app.database.database import db
from app.models.Person import Person


class Director(Person):
    __tablename__ = "Director"

    def __init__(self, name, surname, email, salary, magazine_id, id=None):
        self.id = id
        self.name = name
        self.surname = surname
        self.email = email
        self.salary = salary
        self.magazine_id = magazine_id

flask_app/app/models/Magazine.py
from app.database.database import db


class Magazine(db.Model):
    __tablename__ = "Magazine"

    id = db.Column(db.Integer, primary_key=True)
    city = db.Column(db.String(50))
    street = db.Column(db.String(50))
    postal_code = db.Column(db.String(10), unique=True)
    country = db.Column(db.String(100))
    workers = db.relationship("Worker", backref="magazine", lazy="dynamic")

    def __init__(self, city, street, postal_code, country, id=None):
        self.id = id
        self.city = city
        self.street = street
        self.postal_code = postal_code
        self.country = country

flask_app/app/models/Person.py
from app.database.database import db
from sqlalchemy.orm import declared_attr


class Person(db.Model):
    __tablename__ = "Person"
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True, unique=True, autoincrement=True)
    name = db.Column(db.String(128))
    surname = db.Column(db.String(128))
    email = db.Column(db.String(128), unique=True)
    salary = db.Column(db.Integer)

    @declared_attr
    def magazine_id(self):
        return db.Column(db.Integer, db.ForeignKey("Magazine.id"))

flask_app/app/models/Worker.py
from app.database.database import db
from app.models.Person import Person


class Worker(Person):
    __tablename__ = "Worker"

    shift = db.Column(db.String(128))

    def __init__(self, name, surname, email, salary, shift, magazine_id, id=None):
        self.id = id
        self.name = name
        self.surname = surname
        self.email = email
        self.salary = salary
        self.shift = shift
        self.magazine_id = magazine_id

flask_app/app/models/__init__.py
from os.path import dirname, basename, isfile, join
import glob

database = glob.glob(join(dirname(__file__), "*.py"))
__all__ = [
    basename(f)[:-3] for f in database if isfile(f) and not f.endswith("__init__.py")
]

flask_app/app/__init__.py
from flask import Flask  ## import Flask

app = Flask(__name__)

# from app.controllers import *

flask_app/app/controllers/__init__.py
from os.path import dirname, basename, isfile, join
import glob

controllers = glob.glob(join(dirname(__file__), "*.py"))
__all__ = [
    basename(f)[:-3] for f in controllers if isfile(f) and not f.endswith("__init__.py")
]

flask_app/app/controllers/magazineController.py
from flask import render_template, request
import time
from sqlalchemy.orm import Session
from sqlalchemy import create_engine
from app.models.Worker import Worker
from app.models.Magazine import Magazine
from app.models.Director import Director
import sqlalchemy as db
from sqlalchemy.sql import func
from sqlalchemy import desc

ROWS_PER_PAGE = 20
engine = create_engine("postgresql://flaskapp:flaskapp@localhost:5432/flaskapp", echo=True)


def magazines():
    if request.method == "POST":
        return None
    else:
        page = request.args.get("page", 1, type=int)
        magazines = Magazine.query.paginate(page=page, per_page=ROWS_PER_PAGE)

        return render_template("magazines.html", magazines=magazines)


def magazine(id):
    magazine = Magazine.query.get_or_404(id)
    return render_template("magazine.html", magazine=magazine)


def query1():
    with Session(engine) as session:
        resetSalaries()
        session.expire_all()
        start_time = time.time()
        director = \
            session.query(Director).filter(Director.name == "Sylwia").filter(Director.surname == "Mikołaj").all()[0]
        count = session.query(Worker).filter(Worker.salary < 4000).filter(
            Worker.magazine_id == director.magazine_id).update(
            {"salary": 4000})
        session.commit()
        orm_time = time.time() - start_time

        resetSalaries()
        session.expire_all()
        start_time = time.time()
        session.execute(
            'UPDATE \"Worker\" SET salary = 4000 WHERE salary < 4000 AND magazine_id = \
            (select magazine_id from \"Director\" where name = \'Sylwia\' AND surname = \'Mikołaj\')'
            )
        session.commit()
        sql_time = time.time() - start_time

        return render_template("query1.html", count=count, orm_time=orm_time, sql_time=sql_time)


def query1orm():
    with Session(engine) as session:
        start_time = time.time()
        director = \
            session.query(Director).filter(Director.name == "Sylwia").filter(Director.surname == "Mikołaj").all()[0]
        count = session.query(Worker).filter(Worker.salary < 4000).filter(
            Worker.magazine_id == director.magazine_id).update(
            {"salary": 4000})
        session.commit()
        orm_time = time.time() - start_time

        resetSalaries()
        return render_template("query1orm.html", count=count, orm_time=orm_time)


def resetSalaries():
    with Session(engine) as session:
        session.execute('UPDATE \"Worker\" SET salary = 2000 WHERE salary = 4000 AND magazine_id = 10')
        session.commit()


def query1sql():
    with Session(engine) as session:
        start_time = time.time()
        session.execute('UPDATE \"Worker\" SET salary = 4000 WHERE salary < 4000 AND magazine_id = 10')
        session.commit()
        sql_time = time.time() - start_time

        resetSalaries()
        return render_template("query1sql.html", sql_time=sql_time)


def query2():
    with Session(engine) as session:
        session.expire_all()
        start_time = time.time()
        magazines = session\
            .query(Magazine.id, func.sum(Worker.salary).label('sum'), Magazine.city, Director.name, Director.surname)\
            .join(Worker)\
            .join(Director)\
            .group_by(Magazine.id, Magazine.city, Director.name, Director.surname)\
            .order_by(desc('sum'))\
            .all()

        orm_time = time.time() - start_time
        session.expire_all()
        start_time = time.time()
        magazines2 = session.execute(
            'SELECT "Magazine".id, sum(W.salary) AS sum, "Magazine".city, D.name, D.surname \
            FROM "Magazine" \
            LEFT JOIN "Worker" W ON "Magazine".id = W.magazine_id \
            LEFT JOIN "Director" D on "Magazine".id = D.magazine_id \
            GROUP BY "Magazine".id, city, D.name, D.surname \
            ORDER BY sum DESC;'
        ).all()
        sql_time = time.time() - start_time

        return render_template("query2.html", orm_time=orm_time, sql_time=sql_time)

flask_app/app/controllers/mainController.py
from flask import render_template
from sqlalchemy import create_engine

engine = create_engine("postgresql://flaskapp:flaskapp@db:5432/flaskapp", echo=True)


def index():
    return render_template("index.html")

flask_app/app/database/__init__.py
from os.path import dirname, basename, isfile, join
import glob

database = glob.glob(join(dirname(__file__), "*.py"))
__all__ = [
    basename(f)[:-3] for f in database if isfile(f) and not f.endswith("__init__.py")
]

flask_app/app/routes/__init__.py
from os.path import dirname, basename, isfile, join
import glob

routes = glob.glob(join(dirname(__file__), "*.py"))
__all__ = [
    basename(f)[:-3] for f in routes if isfile(f) and not f.endswith("__init__.py")
]

flask_app/app/routes/routes.py
from flask import Blueprint
from app.controllers.mainController import *
from app.controllers.magazineController import *

blueprint = Blueprint("blueprint", __name__)
blueprint.route("/", methods=["GET"])(index)

blueprint.route("/magazyny/", methods=["GET", "POST"])(magazines)
blueprint.route("/magazyny/<int:id>/", methods=["GET"])(magazine)
blueprint.route("/query1/", methods=["GET"])(query1)
# blueprint.route("/query1/orm", methods=["GET"])(query1orm)
# blueprint.route("/query1/sql", methods=["GET"])(query1sql)
blueprint.route("/query2/", methods=["GET"])(query2)

flask_app/app/templates/index.html
{% block content %}

<div>
    <hr>
    <a href="/magazyny">Magazyny</a> <br />
    <hr>
    <a href="/query1">Query 1 (Update)</a><br />
{#    <a href="/query1/orm">Query 1 orm (Update)</a><br />#}
{#    <a href="/query1/sql">Query 1 sql (Update)</a><br />#}
    <hr>
    <a href="/query2">Query 2 (Select)</a><br />
</div>
{% endblock %}

flask_app/app/templates/magazine.html
<div>
    <a href="/">Back to /</a>
    <hr>
    <div>
        <a href="{{ url_for('blueprint.magazine', id=magazine.id)}}">
            <b>{{ magazine.id }}</b> | {{ magazine.city }} | {{ magazine.street }} | {{ magazine.postal_code }}
        </a> |
{#        <a href="{{ url_for('blueprint.magazine_edit', id=magazine.id)}}">#}
{#            <b>Edit {{ magazine.id }} </b>#}
{#        </a> |#}
{#        <a href="{{ url_for('blueprint.magazine_delete', id=magazine.id)}}">#}
{#            <b>Delete {{ magazine.id }} </b>#}
{#        </a>#}
        {% for worker in magazine.workers %}
            <br>
            --><b>{{ worker.name }} {{ worker.surname }}</b> {{ worker.email }}
        {% endfor %}
    </div>
    <hr>

    <hr>
    <a href="/">Back to /</a>
</div>

flask_app/app/templates/magazines.html
<div>
    {% for magazine in magazines.items %}
    <div>
        <a href="{{ url_for('blueprint.magazine', id=magazine.id)}}">
            <b>{{ magazine.id }}</b> | {{ magazine.city }} | {{ magazine.street }} | {{ magazine.postal_code }} |
        </a> |
{#        <a href="{{ url_for('blueprint.magazine_edit', id=magazine.id)}}">#}
{#            <b>Edit {{ magazine.id }} </b>#}
{#        </a> |#}
{#        <a href="{{ url_for('blueprint.magazine_delete', id=magazine.id)}}">#}
{#            <b>Delete {{ magazine.id }} </b>#}
{#        </a>#}

    </div>
    {% endfor %}
    <hr>


    <div>
        <a href="{{ url_for('blueprint.magazines', page=magazines.prev_num) }}"> &laquo;</a>

        </a>
        {% for page_num in magazines.iter_pages(left_edge=0, right_edge=0, left_current=4, right_current=4) %}

        <a href="{{ url_for('blueprint.magazines', page=page_num) }}">
            {{ page_num }}
        </a>


        {% endfor %}
        <a href="{{ url_for('blueprint.magazines', page=magazines.next_num) }}">

            &raquo;
        </a>
        <p>
            Showing page {{ magazines.page }} of {{ magazines.pages }}
        </p>
    </div>

    <hr>
    <a href="/">Back to /</a>
</div>

flask_app/app/templates/query1.html
<div>
    Count: {{ count }}
    <br />
    <hr>
    SQLalchemy orm query update elapsed time:
    {{orm_time}}
    <br />
    <hr>
    <br />
    SQL query update elapsed time:
    {{sql_time}} <br />
    <hr />
</div>

flask_app/app/templates/query1orm.html
<div>
    Count: {{ count }}
    <br />
    <hr>
    SQLalchemy orm query update elapsed time:
    {{orm_time}}
    <br />
    <hr>
    <a href="/">Back to /</a>
</div>

flask_app/app/templates/query1sql.html
<div>
    Count: {{ count }}
    <br />
    <hr>
    Sql query update elapsed time:
    {{sql_time}}
    <br />
    <hr>
    <a href="/">Back to /</a>
</div>

flask_app/app/templates/query2.html
<div>
    <br />
    <hr>
    SQLalchemy orm query select time:
    {{orm_time}}
    <br />
    <hr>
    <br />
    SQL query select time:
    {{sql_time}} <br />
    <hr />
</div>